exchanges:
  bittrex: https://bittrex.com/api/v1.1/public/getmarkets
  upbit: https://api.upbit.com/v1/market/all
  bithumb: https://api.bithumb.com/public/ticker/ALL
  kucoin: https://api.kucoin.com/v1/market/open/symbols
  poloniex: https://poloniex.com/public?command=returnTicker
  binance: https://api.binance.com/api/v1/exchangeInfo

# site urls to check for updates
sites:
  - 'https://cafe.bithumb.com/boards/43/contents'

data_folder:
  ./data

bot_token:
  bot_token

telegram_ids:
  - 42
  - 1337